"use client";
import {useEffect,useState,useRef} from "react";import {useParams} from "next/navigation";import Link from "next/link";
import {authorRequest,cardFields,newChapter,type Work,type WorkDocument,type Card} from "@/lib/author-api";import "../author.css";
const tabs:Record<string,string>={outline:"大纲",chapters:"章节正文",characters:"人物",scenes:"场景卡",dialogues:"对话卡",foreshadowing:"伏笔",props:"道具",pricing:"收费设置"};
export default function WorkEditor(){const {id}=useParams<{id:string}>();const [work,setWork]=useState<Work|null>(null),[tab,setTab]=useState("outline"),[chapter,setChapter]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[assist,setAssist]=useState(false),[question,setQuestion]=useState("");const body=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{authorRequest<Work>(`/${id}`).then(setWork).catch(e=>setError(e.message))},[id]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",leave);return()=>window.removeEventListener("beforeunload",leave)},[dirty]);
 function change(patch:Partial<WorkDocument>){setWork(w=>w?{...w,document:{...w.document,...patch}}:w);setDirty(true);setNotice("")}
 async function save(){if(!work)return;setBusy(true);setError("");try{const saved=await authorRequest<Work>(`/${id}`,{title:work.title,document:work.document,revision:work.revision},"PUT");setWork(saved);setDirty(false);setNotice("已保存到此浏览器")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function ai(context:string){setAssist(true);setQuestion(context);setNotice("AI候选服务尚未接通。当前可手动创作；不会提供假候选或假质量分。")}
 async function image(file:File|undefined,apply:(value:string)=>void){if(!file)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>400000){setError("图片请选择400KB以内的PNG/JPEG/WebP；单作品草稿总量限制4MB");return}const reader=new FileReader();reader.onload=()=>apply(String(reader.result));reader.onerror=()=>setError("图片读取失败");reader.readAsDataURL(file)}
 if(!work)return <div className="author-page">{error?<p role="alert">{error}</p>:<p>正在读取作品…</p>}<Link href="/works">返回我的作品</Link></div>;
 const d=work.document,current=d.chapters[chapter],cardKey=tab as "characters"|"scenes"|"dialogues"|"foreshadowing";
 function updateChapter(key:string,value:string|number){change({chapters:d.chapters.map((c,i)=>i===chapter?{...c,[key]:value}:c)})}
 function updateCard(i:number,key:string,value:string){change({[cardKey]:d[cardKey].map((c,j)=>i===j?{...c,[key]:value}:c)})}
 const unresolved=d.foreshadowing.filter(c=>c["状态"]!=="已回收");
 return <div className="author-editor"><header className="author-header"><Link href="/works">← 我的作品</Link><input aria-label="作品名称" maxLength={200} value={work.title} disabled={busy} onChange={e=>{setWork({...work,title:e.target.value});setDirty(true)}}/><button className="author-primary" disabled={busy||!work.title.trim()} onClick={save}>{busy?"保存中…":"保存作品"}</button><button onClick={()=>setAssist(!assist)}>辅助</button></header>
 {error&&<p role="alert" className="author-error">{error}</p>}{notice&&<p role="status" className="author-notice">{notice}</p>}
 <fieldset disabled={busy} className="author-layout"><aside className="author-left"><nav>{Object.entries(tabs).map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav><h3>章节</h3>{d.chapters.map((c,i)=><button key={c.id} aria-pressed={chapter===i&&tab==="chapters"} onClick={()=>{setChapter(i);setTab("chapters")}}>{i+1}. {c.title}</button>)}<button onClick={()=>{change({chapters:[...d.chapters,newChapter()]});setChapter(d.chapters.length);setTab("chapters")}}>＋ 添加章节</button></aside>
 <section className="author-center"><h1>{tabs[tab]}</h1>{tab==="outline"&&<><p>{d.locked?"大纲已锁定；后续生成必须遵循此版本。":"请完善大纲，确认后开始正文写作。"}</p>{["主题","背景","主线","关键转折点","结局方向"].map(f=><label key={f}>{f}<textarea value={d.outline[f]||""} readOnly={d.locked} rows={f==="关键转折点"?6:3} onChange={e=>change({outline:{...d.outline,[f]:e.target.value}})}/><button disabled={d.locked} onClick={()=>ai(`大纲：${f}`)}>AI给几个选项</button></label>)}<button onClick={()=>{if(d.locked){if(window.confirm("修改大纲会影响后续章节规划。解锁后请重新核对章节，确认解锁？")){change({locked:false});setNotice("请先保存解锁状态，再修改大纲") }}else if(["主题","背景","主线","关键转折点","结局方向"].some(f=>!d.outline[f]?.trim()))setError("请填写五项大纲后再锁定");else{change({locked:true});setError("")}}}>{d.locked?"解锁修改":"确认并锁定大纲"}</button></>}
 {tab==="chapters"&&current&&<><label>章节名称<input value={current.title} onChange={e=>updateChapter("title",e.target.value)}/></label><details open={!d.locked}><summary>章节规划</summary>{Object.entries({goal:"当前章目标",conflict:"主要冲突",cast:"出场人物",events:"关键事件",previous:"与前章衔接",next:"与后章衔接"}).map(([key,label])=><label key={key}>{label}<textarea rows={2} value={String(current[key as keyof typeof current])} onChange={e=>updateChapter(key,e.target.value)}/></label>)}</details>{!d.locked&&<p>请先确认并锁定大纲，再开始正文写作。</p>}<label>正文<textarea ref={body} readOnly={!d.locked} rows={24} value={current.text} onChange={e=>updateChapter("text",e.target.value)}/></label><div className="author-tags"><button disabled={!d.locked} onClick={()=>{body.current?.focus();body.current?.setSelectionRange(current.text.length,current.text.length);setNotice("已将光标移到章末，可直接续写")}}>继续续写</button><button disabled={!d.locked} onClick={()=>{body.current?.focus();setNotice("请选中正文直接改写，保存后更新草稿版本")}}>改写正文</button><button disabled={!d.locked} onClick={()=>ai(`选区：${current.text.slice(body.current?.selectionStart||0,body.current?.selectionEnd||0)}；章节：${current.title}`)}>选中文字向AI提问</button><button onClick={()=>setNotice(`待检查：大纲一致性、人物一致性、时间线、前章衔接尚未接通语义服务；当前未回收伏笔${unresolved.length}条。`)}>质量检查</button></div></>}
 {cardFields[tab]&&<><button onClick={()=>change({[cardKey]:[...d[cardKey],{id:crypto.randomUUID(),...(tab==="foreshadowing"?{"状态":"已埋设","重要度":"中"}:{})}]})}>＋ 新建{tabs[tab]}</button>{d[cardKey].map((card,i)=><details key={card.id||i} className="author-card" open><summary>{card[cardFields[tab][0]]||`${tabs[tab]} ${i+1}`}</summary>{cardFields[tab].map(f=><label key={f}>{f}{f==="状态"?<select value={card[f]||"已埋设"} onChange={e=>updateCard(i,f,e.target.value)}>{["已埋设","已暗示","已揭示","已回收"].map(t=><option key={t}>{t}</option>)}</select>:<textarea rows={2} value={card[f]||""} onChange={e=>updateCard(i,f,e.target.value)}/>}<button onClick={()=>ai(`${tabs[tab]} ${i+1}：${f}`)}>AI给几个选项</button></label>)}{["characters","scenes"].includes(tab)&&<label>上传或更换图片{card.image&&<img className="author-preview" src={card.image} alt="当前素材预览"/>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>image(e.target.files?.[0],v=>updateCard(i,"image",v))}/></label>}<button onClick={()=>{if(window.confirm("删除此卡片？已有章节中的引用需手动检查。"))change({[cardKey]:d[cardKey].filter((_,j)=>j!==i)})}}>删除卡片</button></details>)}</>}
 {tab==="props"&&<><button onClick={()=>change({props:[...d.props,{id:crypto.randomUUID(),name:"新道具",description:"",image:"",price:0}]})}>＋ 添加道具</button>{d.props.map((p,i)=><section className="author-card" key={p.id}><label>道具名称<input value={p.name} onChange={e=>change({props:d.props.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label><label>描述<textarea value={p.description} onChange={e=>change({props:d.props.map((x,j)=>j===i?{...x,description:e.target.value}:x)})}/></label>{p.image&&<img className="author-preview" src={p.image} alt={p.name}/>}<label>上传或替换图片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>image(e.target.files?.[0],v=>change({props:d.props.map((x,j)=>j===i?{...x,image:v}:x)}))}/></label></section>)}</>}
 {tab==="pricing"&&<><p>仅保存收费草稿，未发布生效，也不会扣款。0表示免费，付费价格为1–5000灵晶整数。</p><h2>收费章节</h2>{d.chapters.map((c,i)=><label key={c.id}>{c.title}<input aria-label={`${c.title}价格`} type="number" min={0} max={5000} step={1} value={c.price} onChange={e=>change({chapters:d.chapters.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x)})}/></label>)}<h2>收费道具</h2>{!d.props.length&&<p>先在“道具”页添加道具。</p>}{d.props.map((p,i)=><label key={p.id}>{p.name}<input aria-label={`${p.name}价格`} type="number" min={0} max={5000} step={1} value={p.price} onChange={e=>change({props:d.props.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x)})}/></label>)}</>}
 </section><aside className={`author-right ${assist?"is-open":""}`}><button className="author-mobile-close" onClick={()=>setAssist(false)}>关闭辅助</button><h2>AI帮我写</h2><label>类型<select><option>场景描写</option><option>对话</option><option>过渡</option><option>心理描写</option><option>转折设计</option><option>伏笔设计</option><option>角色出场</option><option>金句设计</option></select></label><label>我来说<textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="描述你的要求，或选中正文后提问"/></label><button onClick={()=>ai(question)}>生成多个候选</button><p className="author-muted">真实AI尚未接通。接通后将提供3–5个候选，由你确认使用。</p><h3>当前章目标</h3><p>{current?.goal||"尚未填写"}</p><h3>出场人物</h3><p>{current?.cast||"尚未填写"}</p><h3>未回收伏笔 · {unresolved.length}</h3>{unresolved.map((f,i)=><p key={i}>{f["伏笔编号"]} {f["伏笔内容"]} · 预计第{f["预计回收章节"]||"?"}章回收</p>)}<h3>前一章结尾</h3><p>{chapter>0?d.chapters[chapter-1].text.slice(-300)||"前章尚无正文":"这是第一章"}</p></aside></fieldset>
 <footer className="author-status">{dirty?"有未保存更改":"已保存"} · 正文 {d.chapters.reduce((n,c)=>n+Array.from(c.text).length,0)} 字符 · 版本 v{work.revision} · 质量：未评估</footer></div>
}
