"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import Link from "next/link";
import {genres,narrativeTags} from "@/lib/genres";import {authorRequest,newChapter,type Work,type WorkDocument} from "@/lib/author-api";import "../works/author.css";
const steps=[{title:"你想写一个什么样的故事？",fields:["故事名","创意概要"]},{title:"你的主角是什么样的人？",fields:["主角类型","职业身份","核心性格"]},{title:"故事的核心矛盾是什么？",fields:["冲突类型","内在驱动力"]},{title:"世界是什么样的？",fields:["世界观设定"]},{title:"谁会走进主角的故事？",fields:["重要配角（建议至少3位）"]},{title:"他们之间有什么关系？",fields:["关系网络"]},{title:"你希望故事有多长？",fields:["故事长度","目标字数"]},{title:"你想带给读者什么感受？",fields:["情感基调"]},{title:"故事会走向怎样的结局？",fields:["结局方向"]}];
const options:Record<string,string[]>={"主角类型":["单主角","双主角","群像"],"职业身份":["学生","职场人","修行者","侦探","其他"],"核心性格":["热血","冷静","腹黑","温柔"],"冲突类型":["生存危机","真相追寻","复仇之路","权力争夺","情感纠葛","自我成长"],"内在驱动力":["守护某人","证明自己","寻找真相"],"故事长度":["短篇","中篇","长篇"],"情感基调":["轻松","沉重","热血","治愈","暗黑"],"结局方向":["悲剧","喜剧","开放","多结局"]};
export default function Simulator(){const router=useRouter();const [step,setStep]=useState(0),[brief,setBrief]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(""),[group,setGroup]=useState("玄幻"),[custom,setCustom]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const toggle=(tag:string)=>setSelected(x=>x.includes(tag)?x.filter(t=>t!==tag):[...x,tag]);
 const next=()=>{if(step<3&&steps[step].fields.some(f=>!brief[f]?.trim())){setError("请回答本页核心问题，也可以自由描述");return}if(step===0&&!selected.length){setError("请选择或自定义至少一个题材");return}setError("");setStep(step+1)};
 async function create(){setBusy(true);setError("");const document:WorkDocument={brief,genres:selected,outline:{主题:"",背景:brief["世界观设定"]||"",主线:brief["创意概要"]||"",关键转折点:"",结局方向:brief["结局方向"]||""},locked:false,chapters:[newChapter()],characters:[],scenes:[],dialogues:[],foreshadowing:[],props:[]};try{const work=await authorRequest<Work>("",{title:brief["故事名"],document});router.push(`/works/${work.id}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="author-page"><header className="author-header"><div><p>写一本新小说</p><h1>小说辅助模拟器</h1></div><Link href="/works">我的作品 · 编辑作品</Link></header><p className="author-muted">大纲是骨架，章节是血肉。你决定故事，AI负责协助。</p><div className="author-steps">核心三问 → 深度定制（可跳过） → 创作简报 → 锁定大纲 → 逐章创作</div>{error&&<p role="alert" className="author-error">{error}</p>}
 {step<steps.length?<section className="author-question"><p className="author-muted">{step+1} / {steps.length} · {step<3?"必答":"选答"}</p><h2>{steps[step].title}</h2>{step===0&&<><label>搜索题材<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如：赛博朋克、悬疑爱情、乡土…"/></label><div className="author-tags">{Object.keys(genres).map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="author-tags">{(query?Object.values(genres).flat().filter(t=>t.includes(query)):genres[group]).map(t=><button key={t} aria-pressed={selected.includes(t)} onClick={()=>toggle(t)}>{t}</button>)}</div><details><summary>背景、叙事与人物标签</summary><div className="author-tags">{narrativeTags.map(t=><button key={t} aria-pressed={selected.includes(t)} onClick={()=>toggle(t)}>{t}</button>)}</div></details><div className="author-inline"><input aria-label="自定义题材" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="自定义或交叉题材"/><button onClick={()=>{if(custom.trim()&&!selected.includes(custom.trim()))toggle(custom.trim());setCustom("")}}>添加题材</button></div><p>已选：{selected.join(" / ")||"尚未选择"}</p></>}
 {steps[step].fields.map(f=><label key={f}>{f}{options[f]&&<div className="author-tags">{options[f].map(t=><button key={t} aria-pressed={brief[f]===t} onClick={()=>setBrief({...brief,[f]:t})}>{t}</button>)}</div>}<textarea aria-label={f} value={brief[f]||""} onChange={e=>setBrief({...brief,[f]:e.target.value})} placeholder="自由描述你的想法" rows={f==="故事名"?1:3}/></label>)}<button onClick={()=>setError("AI候选服务尚未接通；你可以选择题材和提示选项，或自由描述。不会自动编造生成结果。")}>AI随机生成</button><div className="author-actions"><button disabled={step===0} onClick={()=>{setStep(step-1);setError("")}}>上一步</button><button className="author-primary" onClick={next}>{step<3?"确认，下一问":"下一问 / 跳过此项"}</button></div></section>:<section className="author-question"><h2>创作简报</h2><p>{selected.join(" / ")}</p>{Object.entries(brief).map(([k,v])=><p key={k}><strong>{k}：</strong>{v||"未填写"}</p>)}<div className="author-actions"><button onClick={()=>setStep(0)}>重新调整</button><button className="author-primary" disabled={busy} onClick={create}>{busy?"正在保存…":"确认，进入大纲编辑"}</button></div></section>}</div>
}
