"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import * as Dialog from "@radix-ui/react-dialog";
import {API_BASE_URL} from "@/lib/api";
import "./world.css";
const demo=["夜色漫过湖面，远山沉入薄雾。廊下的一盏灯仍亮着。你循着水声走来，停在亭前。", "沈照月转过身，将手中的信笺轻轻收起。\n“你来了。今夜的风，比昨日更凉一些。”", "她望向对岸。那里没有灯，只有一条被月光照亮的小径。\n你还记得，那是你们初次相遇的地方。", "“有些故事，读到这里便结束了。”她说。\n“但如果你愿意，我们可以从这一页，重新开始。”", "你在长廊坐下。茶水微温，风吹过竹帘。方才没有问出口的话，此刻似乎也不必急着说。", "湖心的月影轻轻晃动。你翻开书，新的篇章在灯下展开。"];
function paginate(original:string){const chars=Array.from(original),pages:string[]=[];let start=0;while(start<chars.length){let end=Math.min(start+180,chars.length);if(end<chars.length){for(let i=end;i>start+90;i--)if(/[。！？\n]/.test(chars[i-1])){end=i;break}}pages.push(chars.slice(start,end).join(""));start=end}return pages;}
export default function World(){
 const [pages,setPages]=useState(demo),[title,setTitle]=useState("月下长廊"),[source,setSource]=useState("demo"),[index,setIndex]=useState(0),[shown,setShown]=useState(0),[mode,setMode]=useState("read"),[auto,setAuto]=useState(false),[panel,setPanel]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const text=pages[index]||"",chars=Array.from(text),complete=shown>=chars.length;
 useEffect(()=>{let alive=true;const id=new URLSearchParams(location.search).get("source");if(!id){setLoading(false);return}setSource(id);fetch(`${API_BASE_URL}/creator/sources/${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(typeof data.detail==="string"?data.detail:"原稿读取失败");if(!data.integrity?.valid)throw Error("原稿完整性未通过");if(alive){setPages(paginate(data.original));setTitle(data.title);setIndex(0)}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
 useEffect(()=>{setShown(0)},[index,pages]);
 useEffect(()=>{if(loading||panel||complete)return;if(matchMedia("(prefers-reduced-motion: reduce)").matches){setShown(chars.length);return}const timer=setTimeout(()=>setShown(n=>n+2),35);return()=>clearTimeout(timer)},[shown,chars.length,complete,panel,loading]);
 useEffect(()=>{if(!auto||!complete||panel||loading||error)return;const timer=setTimeout(()=>{if(document.hidden){setAuto(false);return}if(index<pages.length-1)setIndex(n=>n+1);else setAuto(false)},Math.max(2400,chars.length*65));return()=>clearTimeout(timer)},[auto,complete,panel,index,pages.length,loading,error,chars.length]);
 useEffect(()=>{const hide=()=>{if(document.hidden)setAuto(false)};document.addEventListener("visibilitychange",hide);return()=>document.removeEventListener("visibilitychange",hide)},[]);
 function next(){if(!complete)setShown(chars.length);else if(index<pages.length-1)setIndex(index+1);else {setAuto(false);setMessage("已读完全部内容")}}
 function save(){try{localStorage.setItem(`lingjing-vn:${source}`,JSON.stringify({source,index,mode,total:pages.length}));setMessage("已保存到此浏览器")}catch{setMessage("此浏览器无法保存，请检查存储权限")}}
 function load(){try{const raw=localStorage.getItem(`lingjing-vn:${source}`);if(!raw){setMessage("此作品暂无本地存档");return}const d=JSON.parse(raw);if(d.source!==source||d.total!==pages.length||!Number.isInteger(d.index)||d.index<0||d.index>=pages.length||!["read","explore"].includes(d.mode))throw Error();setIndex(d.index);setMode(d.mode);setAuto(false);setMessage("已读取本地存档")}catch{setMessage("存档无效，当前进度已保留")}}
 return <main className="vn-stage" aria-label="小说世界">
 <div className="vn-background"/><div className="vn-shade"/>
 <header className="vn-header"><Link className="vn-brand" href="/stories">灵境 <small>· 双生</small></Link><div className="vn-title">{title}<small>{source==="demo"?"原创演出样例 · 非原著 / 非AI支线":"原稿演出阅读 · 通用场景背景"}</small></div><Link href="/companion">心屿</Link><Link href="/creator">写新小说</Link></header>
 <nav className="vn-mode" aria-label="游玩模式"><button aria-pressed={mode==="read"} onClick={()=>setMode("read")}>沉浸阅读</button><button aria-pressed={mode==="explore"} onClick={()=>{setMode("explore");setAuto(false)}}>自由探索</button></nav>
 {!loading&&!error&&<><div className="vn-location"><span>◈</span>{source==="demo"?"湖畔 · 月下长廊":"原稿剧场"}<small>{index+1} / {pages.length}</small></div>
 {source==="demo"&&<img className="vn-character" src="output/latest/assets/moon-guide.png" alt="沈照月，身着青色衣裙的成年女子"/>}
 {mode==="explore"&&<div className="vn-hotspots">{source==="demo"?<><button onClick={()=>{setPanel("scene");setAuto(false)}}>◈ 查看信笺</button><button onClick={()=>{setPanel("character");setAuto(false)}}>◇ 沈照月</button></>:<button onClick={()=>setPanel("explore")}>查看探索状态</button>}</div>}
 <section className="vn-dialogue" aria-label="原文演出"><div className="vn-speaker">{source==="demo"?(index===1||index===3?"沈照月":"旁白"):"原文"}<span>{mode==="read"?"沉浸阅读":"自由探索"}</span></div><button className="vn-text" onClick={next} aria-label={complete?"继续阅读":"显示本段全文"}><span aria-hidden="true">{chars.slice(0,shown).join("")}</span><span className="vn-sr">{text}</span></button><div className="vn-dialogue-bottom"><span>{complete?(index===pages.length-1?"本篇已至末页":"点击正文继续") :"点击显示全文"}</span><button onClick={next}>{complete?"继续 ▷":"显示全文"}</button></div></section>
 <footer className="vn-toolbar"><button disabled={index===0} onClick={()=>{setIndex(index-1);setAuto(false)}}>上一段</button><button aria-pressed={auto} onClick={()=>setAuto(!auto)}>{auto?"暂停自动":"自动阅读"}</button><button onClick={()=>{setPanel("history");setAuto(false)}}>阅读记录</button><button onClick={save}>存档</button><button onClick={load}>读档</button><Link href="/stories">返回书库</Link></footer></>}
 {loading&&<div className="vn-center" role="status">正在展开原稿…</div>}{error&&<div className="vn-center" role="alert">{error}<br/><Link href="/creator">返回原稿工作台</Link></div>}
 {message&&<button className="vn-toast" role="status" onClick={()=>setMessage("")}>{message} ×</button>}
 <Dialog.Root open={!!panel} onOpenChange={open=>{if(!open)setPanel("")}}><Dialog.Portal><Dialog.Overlay className="vn-overlay"/><Dialog.Content aria-describedby={undefined} className="vn-panel vn-modal"><button autoFocus className="vn-close" onClick={()=>setPanel("")}>关闭 ×</button><Dialog.Title>{panel==="history"?"阅读记录":panel==="character"?"沈照月":panel==="scene"?"灯下的信笺":"自由探索"}</Dialog.Title>{panel==="history"?pages.slice(0,index+1).map((p,i)=><p className="vn-history" key={i}><small>第 {i+1} 段</small>{p}</p>):<><p>{panel==="character"?"原创演出人物。此处展示人物出场与场景交互的表现形式。":panel==="scene"?"一封尚未拆开的信，静静放在灯旁。这是演出样例的场景注释，不修改正文，也不改变存档状态。":"当前原稿尚未配置交互锚点。你可以继续完整阅读。"}</p><p>动态支线与行动判定尚未接通。不会用预设文字冒充 AI 生成结果。</p><button onClick={()=>{setPanel("");setMode("read")}}>继续阅读</button></>}</Dialog.Content></Dialog.Portal></Dialog.Root>
 </main>
}
