from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_context(viewport={'width': 480, 'height': 800}).new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(getattr(e, 'stack', None) or str(e)))
    page.on('console', lambda m: errors.append(f'console.{m.type}: {m.text}') if m.type in ('error', 'warning') else None)
    page.goto('http://127.0.0.1:8767/novel-game.html?demo=1', wait_until='domcontentloaded')
    page.wait_for_function('window.NovelWorldFlow && window.NovelWorldVN', timeout=10000)
    page.wait_for_timeout(800)
    print('1. window.state:', page.evaluate('!!window.state'))
    print('2. state.book:', page.evaluate('!!(window.state && window.state.book)'))
    print('3. entry-mask open:', page.evaluate('document.querySelector("#ng-entry-mask") && document.querySelector("#ng-entry-mask").classList.contains("open")'))
    print('4. splash visible:', page.evaluate('(() => { var el = document.querySelector("#ng-splash"); return el ? (getComputedStyle(el).display !== "none") : "no-el"; })()'))
    print('5. splash-start exists:', page.evaluate('!!document.querySelector("#ng-splash-start")'))
    page.evaluate('var eb = document.querySelector("#ng-entry-back"); if (eb) eb.click();')
    page.wait_for_timeout(200)
    print('6. splash-start has size:', page.evaluate('(() => { var el = document.querySelector("#ng-splash-start"); if (!el) return false; var r = el.getBoundingClientRect(); return r.width > 0 && r.height > 0; })()'))
    print('7. v22Store before click:', page.evaluate('(window.state && window.state.v22Store) ? "already" : "not-yet"'))
    page.evaluate('document.querySelector("#ng-splash-start").click()')
    page.wait_for_timeout(1200)
    print('8. v22Store after click:', page.evaluate('!!(window.state && window.state.v22Store)'))
    print('9. v22Player:', page.evaluate('!!(window.state && window.state.v22Player)'))
    print('10. container display:', page.evaluate('(() => { var el = document.querySelector("#ng-v22-container"); return el ? getComputedStyle(el).display : "no-el"; })()'))
    print('11. errors:', errors[:6])
    browser.close()
