"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AnimatePresence,motion } from "framer-motion";
import { Button } from "@/components/ui/Button";
import { useProfileStore } from "@/store/useProfileStore";
import { useCharacterStore } from "@/store/useCharacterStore";
export default function OnboardingPage(){
 const router=useRouter(),{load:loadProfile,save}=useProfileStore(),{load:loadCharacters,select}=useCharacterStore();
 const [step,setStep]=useState(0),[nickname,setNickname]=useState(''),[companion,setCompanion]=useState('preset_ling'),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;Promise.all([loadProfile(),loadCharacters()]).then(([p])=>{if(alive&&p.onboarded)router.replace('/')}).catch(()=>{if(alive)setError('暂时无法连接服务。请确认后端运行后重试。')});return()=>{alive=false}},[loadProfile,loadCharacters,router]);
 async function finish(destination:string){setSaving(true);setError('');try{await save({nickname:nickname.trim(),onboarded:true,companion_id:companion});select(companion);router.replace(destination)}catch{setError('保存未完成，你填写的内容已保留，请重试。')}finally{setSaving(false)}}
 return <div className="mx-auto grid min-h-screen max-w-[1600px] lg:grid-cols-[1.05fr_1fr]">
 <section className="relative hidden min-h-screen overflow-hidden bg-[#1c2835] lg:block" aria-label="角色插画"><img src="/assets/characters/ling-realistic-v1.png" alt="灵，写实风格的成年虚构角色" className="absolute inset-0 h-full w-full object-cover object-[50%_30%]"/><div className="absolute inset-0 bg-gradient-to-t from-[#0f1725] via-[#0f1725]/10 to-transparent"/><Link href="/stories" className="absolute left-12 top-10 flex items-center gap-3 text-lg font-semibold"><img src="/icon.svg" alt="" className="h-10 w-10"/>MIRAI 灵境</Link><div className="absolute inset-x-12 bottom-14"><p className="mb-3 text-sm text-white/65">角色陪伴与平行人生</p><h1 className="font-display text-4xl leading-relaxed">相遇，从你的选择开始。</h1><p className="mt-5 max-w-md text-sm leading-7 text-white/65">在熟悉的故事里成为另一个自己，也在日常的对话中，留下属于你的记忆。</p></div></section>
 <section className="flex min-h-screen flex-col px-6 py-8 sm:px-14 lg:px-16"><header className="flex items-center justify-between"><Link href="/stories" className="text-sm text-white/60 lg:invisible">MIRAI 灵境</Link><a className="text-xs text-[#b6a6df]" href="/development-progress.html">查看开发进度</a></header>
 <div className="mx-auto flex w-full max-w-md flex-1 flex-col justify-center py-12"><div className="mb-10 flex gap-2" aria-label={`引导步骤 ${step+1}/3`}>{[0,1,2].map(i=><span key={i} className={`h-1 w-10 rounded-full ${i<=step?'bg-[#b6a6df]':'bg-white/10'}`}/>)}</div>
 <AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.18}}>
 {step===0&&<><p className="mb-4 text-sm text-[#b6a6df]">欢迎来到灵境</p><h2 className="text-3xl font-semibold leading-snug">故事里的下一页，<br/>由你来写。</h2><p className="mt-6 text-sm leading-8 text-[#9faec2]">选择人物进入小说世界，经历相遇、抉择与不同的结局。也可以创建自己的伙伴，慢慢建立共同的记忆。</p><div className="my-8 divide-y divide-white/10"><p className="py-4 text-sm"><i aria-hidden="true" className="fa-solid fa-book-open mr-4 text-[#b6a6df]"/>探索多路线互动故事</p><p className="py-4 text-sm"><i aria-hidden="true" className="fa-solid fa-user-group mr-4 text-[#b6a6df]"/>创建你的人物与陪伴关系</p><p className="py-4 text-sm"><i aria-hidden="true" className="fa-solid fa-bookmark mr-4 text-[#b6a6df]"/>回看经历，收藏命运卡</p></div><Button size="lg" className="w-full" onClick={()=>setStep(1)}>开始设置</Button><Link href="/stories" className="mt-5 block text-center text-sm text-white/50">先看看故事书库</Link></>}
 {step===1&&<><h2 className="text-3xl font-semibold">希望怎么称呼你？</h2><p className="my-5 text-sm leading-7 text-[#9faec2]">这里的昵称用于界面称呼。进入不同故事时，你还可以选择新的身份。</p><label className="mb-2 block text-sm" htmlFor="nickname">你的昵称</label><input id="nickname" autoFocus value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={20} onKeyDown={e=>{if(e.key==='Enter'&&nickname.trim())setStep(2)}} placeholder="输入昵称" className="h-14 w-full rounded-xl border border-[#344058] bg-[#182231] px-4 text-lg"/><div className="mt-8 flex gap-3"><Button variant="ghost" onClick={()=>setStep(0)}>返回</Button><Button size="lg" className="flex-1" disabled={!nickname.trim()} onClick={()=>setStep(2)}>继续</Button></div></>}
 {step===2&&<><h2 className="text-3xl font-semibold">选择第一位伙伴</h2><p className="my-5 text-sm leading-7 text-[#9faec2]">{nickname}，从一次简单的相遇开始。之后可以在人物工作室创建自己的角色。</p><div role="radiogroup" aria-label="选择伙伴" className="grid gap-3">{[{id:'preset_ling',name:'灵',description:'温柔、敏锐，擅长倾听。'},{id:'preset_xiaoman',name:'小满',description:'元气、直率，喜欢分享日常。'}].map(c=><button role="radio" aria-checked={companion===c.id} tabIndex={companion===c.id?0:-1} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'preset_ling':e.key==='End'?'preset_xiaoman':companion==='preset_ling'?'preset_xiaoman':'preset_ling';setCompanion(next);const group=e.currentTarget.parentElement;requestAnimationFrame(()=>group?.querySelector<HTMLButtonElement>('[aria-checked="true"]')?.focus())}}} key={c.id} onClick={()=>setCompanion(c.id)} className={`flex items-center gap-4 rounded-2xl border p-4 text-left ${companion===c.id?'border-[#b6a6df] bg-[#28324a]':'border-[#344058] bg-[#182231]'}`}>{c.id==='preset_ling'?<img src="/assets/characters/ling-realistic-v1.png" alt="" className="h-16 w-16 rounded-xl object-cover"/>:<span className="flex h-16 w-16 items-center justify-center rounded-xl bg-[#334152] text-2xl">满</span>}<span className="flex-1"><strong className="block font-medium">{c.name}</strong><span className="mt-1 block text-xs text-[#9faec2]">{c.description}</span></span><i aria-hidden="true" className={`fa-regular ${companion===c.id?'fa-circle-check':'fa-circle'} text-[#b6a6df]`}/></button>)}</div><div className="mt-8 grid gap-3"><Button size="lg" disabled={saving} onClick={()=>void finish('/stories')}>{saving?'正在保存…':'进入故事书库'}</Button><Button variant="glass" disabled={saving} onClick={()=>void finish('/')}>先与伙伴聊天</Button><Button variant="ghost" disabled={saving} onClick={()=>setStep(1)}>返回</Button></div></>}
 </motion.div></AnimatePresence>{error&&<div role="alert" className="mt-5 rounded-xl border border-red-300/20 bg-red-300/5 p-4 text-sm leading-6 text-red-200">{error}<button className="ml-2 underline" onClick={()=>window.location.reload()}>重新连接</button></div>}</div>
 <footer className="mx-auto max-w-md text-xs leading-6 text-[#75859b]">开发体验版 · AI角色是虚构人物，不代表真实人格或情感。产品不提供心理诊断与治疗；正式实名及年龄核验尚未接通。</footer>
 </section></div>
}
